import { registerContent } from '@/content/index'

registerContent('p9-controlnet-dreambooth', () => ({
  difficulty: 'Advanced',
  estimatedTime: '60 minutes',
  prerequisites: ['p9-stable-diffusion', 'p8-lora-qlora'],
  tags: ['Generative AI', 'Advanced', 'Topic'],
  objectives: [
    'Understand how ControlNet provides spatial control over Stable Diffusion generation',
    'Implement ControlNet pipelines with edge, depth, and pose conditioning',
    'Understand DreamBooth fine-tuning with class-specific prior preservation loss',
    'Compare DreamBooth, LoRA, and Textual Inversion for personalization',
  ],
  theory: `# ControlNet & DreamBooth

## ControlNet: Adding Spatial Control

ControlNet (Zhang & Agrawala, 2023) adds spatial conditioning to pretrained diffusion models by freezing the original model and training a **trainable copy** of the U-Net encoder. This preserves the original model's knowledge while adding new control signals.

### Zero Convolution

The key architectural innovation is **zero convolution** — 1x1 convolution layers initialized to zero weight and bias. During training, the zero convolutions gradually learn to propagate the conditioning signal:

$$\\mathcal{Z}(x; \\Theta) = \\Theta_1 \\cdot x + \\Theta_2 \\quad \\text{with} \\quad \\Theta_1 = 0, \\Theta_2 = 0 \\text{ initially}$$

This ensures that at the start of training, the ControlNet does not affect the pretrained model. The effect grows gradually as training progresses, preventing catastrophic forgetting of the original model's capabilities.

### Architecture

1. **Original U-Net** (frozen): The pretrained Stable Diffusion U-Net remains unchanged
2. **ControlNet copy** (trainable): A trainable copy of the U-Net encoder blocks
3. **Zero convolutions**: Connect each ControlNet encoder block to the corresponding decoder block in the original U-Net
4. **Conditioning input**: Canny edges, depth maps, pose skeletons, or any other spatially aligned signal

The ControlNet output at each resolution level is:

$$y_c = \\mathcal{F}(x; \\Theta_c) + \\mathcal{Z}(\\mathcal{F}(x + c; \\Theta_z); \\Theta_{zero})$$

Where $c$ is the conditioning image, $\\mathcal{F}$ is the encoder block, and $\\mathcal{Z}$ is zero convolution.

### Conditioning Types

**Canny Edge**: Extracts edges from a reference image using the Canny edge detector. Best for preserving exact composition and structure.

**Depth**: Uses MiDaS or ZoeDepth to estimate depth maps. Provides 3D structural guidance while allowing texture and color freedom.

**OpenPose**: Extracts human pose skeletons (keypoints for body, hands, face). Enables precise pose control for character generation.

**HED (Holistically-Nested Edge Detection)**: Soft edge detection that preserves more detail than Canny. Better for organic subjects.

**Normal Maps / Surface Normals**: Provides surface orientation information. Useful for 3D-aware generation and object re-lighting.

### Multi-ControlNet

Multiple ControlNets can be combined by weighting their contributions:

$$\\epsilon_\\theta(z_t, t, c_1, c_2) = \\epsilon_\\theta(z_t, t) + \\sum_i w_i \\cdot \\Delta_i(z_t, t, c_i)$$

Where $w_i$ are per-ControlNet weights and $\\Delta_i$ are the individual conditioning contributions.

## DreamBooth: Personalization

DreamBooth (Ruiz et al., 2023) fine-tunes a pretrained text-to-image model to generate a specific subject (e.g., a particular dog, person, or object) in diverse contexts using just a few images (typically 3-10).

### Unique Token Identifier

DreamBooth assigns a unique token (e.g., "sks") to the subject by fine-tuning on the provided images with a prompt like:

> "a [unique identifier] [class noun]"

For example: "a sks dog" where "sks" maps to the specific dog and "dog" is the class.

### Class-Specific Prior Preservation Loss

The key innovation preventing overfitting and catastrophic forgetting is the **prior preservation loss**. During fine-tuning, the model must also generate images of the **class** without the specific subject:

$$\\mathcal{L}_{prior} = \\mathbb{E}_{x_{pr}, t, \\epsilon} \\left[ \\|\\epsilon - \\epsilon_\\theta(x_{pr,t}, t, c_{pr})\\|^2 \\right]$$

Where $x_{pr}$ are images generated by the frozen pretrained model of the class (e.g., "dog") and $c_{pr}$ is the class prompt.

The total loss is:

$$\\mathcal{L} = \\mathcal{L}_{recon} + \\lambda_{prior} \\mathcal{L}_{prior}$$

The prior preservation term prevents the model from forgetting what a "dog" looks like in general, ensuring the subject can be generated in diverse contexts.

### DreamBooth vs LoRA vs Textual Inversion

**DreamBooth**: Fine-tunes the entire U-Net (large model ~5GB). Best quality but requires more GPU memory and storage.

**LoRA**: Adds low-rank adaptation matrices to cross-attention layers (~10MB). Good quality, fast training, small file size. Most popular for personalization.

**Textual Inversion**: Learns only new word embeddings (no model changes, ~100KB). Lowest quality but most storage-efficient.

## IP-Adapter

IP-Adapter (Ye et al., 2023) enables image-prompted generation by adding **decoupled cross-attention** layers that attend to CLIP image embeddings:

$$\\text{Attention}(Q, K_t, V_t) + \\text{Attention}(Q, K_i, V_i)$$

Where $K_t, V_t$ are from text embeddings and $K_i, V_i$ are from image embeddings. This enables "image prompting" — generating images that capture the style or content of a reference image.`,
  understanding: {
    analogy: 'Think of ControlNet as giving a photographer detailed pose instructions while they work. You hand them a sketch showing exactly where the subject should be, how their body is positioned, and the depth of the scene. But you let the photographer decide the colors, lighting, textures, and fine details. The "zero convolution" is like the photographer initially ignoring your instructions (they\'re trained to work independently), then gradually learning to follow them as they practice. DreamBooth is different — it\'s like teaching a photographer about a new, specific subject they\'ve never seen before. You show them 5 photos of your dog "Max" and say "learn what Max looks like." The prior preservation loss is like also showing them photos of other dogs to ensure they don\'t forget what "dog" means in general. After training, they can photograph "Max" in any setting — sitting on a beach, running through a field, wearing a hat.',
    steps: [
      { title: 'Prepare Conditioning', content: 'Generate a spatial conditioning signal from a reference image or direct input: Canny edges (OpenCV), depth map (MiDaS), pose skeleton (OpenPose), or user sketch.' },
      { title: 'ControlNet Encoding', content: 'Pass the conditioning image through the ControlNet encoder (trainable copy of U-Net encoder). At each resolution, the output is added to the original U-Net decoder skip connections via zero convolutions.' },
      { title: 'Zero Convolution Fusion', content: 'The zero-convolution outputs start at zero and gradually learn to modulate the pretrained U-Net\'s features. This preserves the original model\'s knowledge while incorporating the new conditioning.' },
      { title: 'Conditional Denoising', content: 'The U-Net denoises the latent while attending to both the text prompt (via cross-attention) and the spatial conditioning (via ControlNet features).' },
      { title: 'Multi-Control Fusion', content: 'When using multiple ControlNets (e.g., Canny + Depth), each contributes its delta to the noise prediction, weighted by user-specified coefficients.' },
    ],
    misconceptions: [
      { misconception: 'ControlNet requires retraining the entire Stable Diffusion model', truth: 'ControlNet is trained separately while the original U-Net is frozen. The control weights are small (~300MB vs 5GB for the full model) and can be swapped without affecting the base model.' },
      { misconception: 'DreamBooth can be trained with a single image', truth: 'While possible, 3-10 images from different angles/contexts produce much better results. Too few images cause overfitting (the subject looks identical in every generated image) and catastrophic forgetting.' },
      { misconception: 'LoRA is always worse than DreamBooth', truth: 'LoRA often matches DreamBooth quality for subject/style personalization while being 500x smaller and training 3x faster. DreamBooth still excels for complex subjects requiring full model adaptation.' },
    ],
    comparisons: [
      { label: 'Storage Size', methodA: '~5GB (full U-Net fine-tune)', methodB: '~10MB (low-rank matrices)' },
      { label: 'Training Time', methodA: '10-30 minutes (A100)', methodB: '2-5 minutes (A100)' },
      { label: 'Subject Fidelity', methodA: 'Excellent', methodB: 'Very Good' },
      { label: 'Class Retention', methodA: 'Prior preservation loss helps', methodB: 'Inherently preserves via frozen weights' },
    ],
  },
  codeExamples: [
    {
      level: 'basic',
      code: `import torch
from diffusers import (
    StableDiffusionControlNetPipeline,
    ControlNetModel,
    DDIMScheduler,
)
from diffusers.utils import load_image
import cv2
import numpy as np

# ============ Canny Edge ControlNet ============

controlnet = ControlNetModel.from_pretrained(
    "lllyasviel/sd-controlnet-canny",
    torch_dtype=torch.float16,
)

pipe = StableDiffusionControlNetPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5",
    controlnet=controlnet,
    torch_dtype=torch.float16,
    safety_checker=None,
)
pipe.scheduler = DDIMScheduler.from_config(pipe.scheduler.config)
pipe = pipe.to("cuda" if torch.cuda.is_available() else "cpu")

def get_canny_edges(image_path, low_threshold=100, high_threshold=200):
    """Extract Canny edges from an image for ControlNet conditioning."""
    image = cv2.imread(image_path)
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    image = cv2.resize(image, (512, 512))
    edges = cv2.Canny(image, low_threshold, high_threshold)
    edges = cv2.cvtColor(edges, cv2.COLOR_GRAY2RGB)
    return edges

# Generate from edges
edges = get_canny_edges("reference_building.png")
edges_image = Image.fromarray(edges)

prompt = "a photograph of a modern building, cinematic lighting, detailed"
negative_prompt = "blurry, low quality, distorted"

image = pipe(
    prompt,
    negative_prompt=negative_prompt,
    image=edges_image,
    num_inference_steps=30,
    guidance_scale=7.5,
    controlnet_conditioning_scale=0.8,
).images[0]

image.save("canny_control_output.png")
print("Canny ControlNet: edges guide the exact composition")

# ============ Depth ControlNet ============

controlnet_depth = ControlNetModel.from_pretrained(
    "lllyasviel/sd-controlnet-depth",
    torch_dtype=torch.float16,
)
pipe_depth = StableDiffusionControlNetPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5",
    controlnet=controlnet_depth,
    torch_dtype=torch.float16,
)
pipe_depth = pipe_depth.to("cuda" if torch.cuda.is_available() else "cpu")

depth_map = load_image("depth_map.png")
depth_output = pipe_depth(
    "a surreal landscape with floating islands",
    image=depth_map,
    num_inference_steps=25,
    controlnet_conditioning_scale=0.9,
).images[0]

print("Depth ControlNet: depth map guides 3D structure")

# ============ Key Parameters ============

print("\\nControlNet parameters:")
print("  controlnet_conditioning_scale: 0-1 (strength)")
print("  Low threshold (Canny): 100 (more edges) - 200 (fewer)")
print("  Guidance scale: 7.5 (typical) for prompt alignment")
print("  Multiple ControlNets: sum weighted contributions")`,
      output: `Canny ControlNet: edges guide the exact composition
Depth ControlNet: depth map guides 3D structure

ControlNet parameters:
  controlnet_conditioning_scale: 0-1 (strength)
  Low threshold (Canny): 100 (more edges) - 200 (fewer)
  Guidance scale: 7.5 (typical) for prompt alignment
  Multiple ControlNets: sum weighted contributions`,
      explanation: 'This demonstrates Canny edge ControlNet and depth ControlNet. The Canny edge detector extracts edges from a reference image, and the ControlNet ensures the generated image follows those edges. The depth ControlNet preserves 3D structure from a depth map. The conditioning_scale controls how strongly the model follows the conditioning signal.',
    },
    {
      level: 'intermediate',
      code: `import torch
from diffusers import (
    StableDiffusionControlNetPipeline,
    ControlNetModel,
    DDIMScheduler,
)
import cv2
import numpy as np

# ============ OpenPose ControlNet ============

controlnet_pose = ControlNetModel.from_pretrained(
    "lllyasviel/sd-controlnet-openpose",
    torch_dtype=torch.float16,
)

pipe_pose = StableDiffusionControlNetPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5",
    controlnet=controlnet_pose,
    torch_dtype=torch.float16,
    safety_checker=None,
)
pipe_pose = pipe_pose.to("cuda" if torch.cuda.is_available() else "cpu")

# Pose skeleton (normally from OpenPose detector)
# Here we simulate with a simple skeleton image
pose_image = load_image("pose_skeleton.png")

prompt = "a powerful warrior with armor, cinematic lighting, epic"
negative_prompt = "extra limbs, distorted, bad anatomy"

pose_output = pipe_pose(
    prompt,
    negative_prompt=negative_prompt,
    image=pose_image,
    num_inference_steps=30,
    guidance_scale=7.5,
    controlnet_conditioning_scale=1.0,
).images[0]

print("OpenPose ControlNet: precise pose control for characters")

# ============ Multi-ControlNet ============

controlnet_canny = ControlNetModel.from_pretrained(
    "lllyasviel/sd-controlnet-canny", torch_dtype=torch.float16
)
controlnet_depth = ControlNetModel.from_pretrained(
    "lllyasviel/sd-controlnet-depth", torch_dtype=torch.float16
)

pipe_multi = StableDiffusionControlNetPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5",
    controlnet=[controlnet_canny, controlnet_depth],
    torch_dtype=torch.float16,
)
pipe_multi = pipe_multi.to("cuda" if torch.cuda.is_available() else "cpu")

# Apply both controls with different weights
multi_image = pipe_multi(
    "a detailed castle on a hill, sunset lighting",
    image=[canny_edges, depth_map],  # Two conditioning images
    num_inference_steps=25,
    controlnet_conditioning_scale=[0.7, 0.4],  # Canny=0.7, Depth=0.4
).images[0]

print("Multi-ControlNet: combines Canny (structure) + Depth (3D)")

# ============ ControlNet with Img2Img ============

from diffusers import StableDiffusionControlNetImg2ImgPipeline

pipe_img2img_control = StableDiffusionControlNetImg2ImgPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5",
    controlnet=controlnet_canny,
    torch_dtype=torch.float16,
)
pipe_img2img_control = pipe_img2img_control.to(
    "cuda" if torch.cuda.is_available() else "cpu"
)

result = pipe_img2img_control(
    "a vibrant oil painting of this scene",
    image=init_image,
    control_image=control_image,
    strength=0.6,
    num_inference_steps=30,
).images[0]

print("ControlNet + Img2Img: transform appearance while preserving structure")

# ============ ControlNet Weight Sweep ============

def controlnet_weight_sweep(pipe, prompt, control_image, scales):
    """Generate with different ControlNet scales."""
    images = []
    for scale in scales:
        img = pipe(
            prompt,
            image=control_image,
            num_inference_steps=20,
            controlnet_conditioning_scale=scale,
        ).images[0]
        images.append(img)
    return images

print("\\nScale sweep:")
print("  0.0 = no control (free generation)")
print("  0.5 = moderate control")
print("  1.0 = strong control (follow conditioning exactly)")`,
      output: `OpenPose ControlNet: precise pose control for characters
Multi-ControlNet: combines Canny (structure) + Depth (3D)
ControlNet + Img2Img: transform appearance while preserving structure

Scale sweep:
  0.0 = no control (free generation)
  0.5 = moderate control
  1.0 = strong control (follow conditioning exactly)`,
      explanation: 'OpenPose ControlNet enables precise character pose control. Multi-ControlNet combines multiple conditioning signals (e.g., Canny for edges + Depth for 3D structure) with independent weights. The img2img variant transforms appearance while preserving the conditioning structure. The scale sweep demonstrates the tradeoff between conditioning fidelity and creative freedom.',
    },
    {
      level: 'advanced',
      code: `import torch
from diffusers import (
    StableDiffusionPipeline,
    DDPMScheduler,
    UNet2DConditionModel,
)
from accelerate import Accelerator

# ============ DreamBooth Training (Simplified) ============

class DreamBoothTrainer:
    """Simplified DreamBooth fine-tuning with prior preservation."""
    def __init__(self, instance_images, instance_prompt,
                 class_prompt="a photo of a dog",
                 num_class_images=100, prior_loss_weight=1.0):
        self.instance_images = instance_images
        self.instance_prompt = instance_prompt
        self.class_prompt = class_prompt
        self.num_class_images = num_class_images
        self.prior_loss_weight = prior_loss_weight

    def prepare_data(self):
        """Prepare instance and class images."""
        # Instance images
        instance_dataset = torch.utils.data.TensorDataset(
            torch.stack([
                self.preprocess(img) for img in self.instance_images
            ])
        )

        # Generate class images (prior preservation)
        # Using frozen pretrained model to avoid data leakage
        pipe = StableDiffusionPipeline.from_pretrained(
            "runwayml/stable-diffusion-v1-5",
            torch_dtype=torch.float16,
        ).to("cuda")

        class_images = []
        for _ in range(self.num_class_images):
            with torch.no_grad():
                image = pipe(
                    self.class_prompt,
                    num_inference_steps=50,
                    guidance_scale=7.5,
                ).images[0]
            class_images.append(image)

        # Free up GPU memory
        del pipe

        return instance_dataset, class_images

    def compute_prior_preservation_loss(self, model, noise_pred,
                                         noise_pred_prior):
        """Compute prior preservation loss.
        
        This penalizes the model for deviating from its pretrained behavior
        on class prompts, preventing catastrophic forgetting.
        """
        return torch.nn.functional.mse_loss(
            noise_pred_prior, noise_pred
        )

    def training_step(self, model, batch, batch_prior):
        """Single training step with prior preservation."""
        # Instance loss
        latents = self.encode(batch["instance_images"])
        noise = torch.randn_like(latents)
        timesteps = torch.randint(0, 1000, (latents.size(0),))
        noisy_latents = self.add_noise(latents, noise, timesteps)
        noise_pred = model(noisy_latents, timesteps,
                           batch["instance_encoder_hidden_states"])

        loss = torch.nn.functional.mse_loss(noise_pred, noise)

        # Prior preservation loss
        if batch_prior is not None:
            with torch.no_grad():
                noise_prior = torch.randn_like(batch_prior["latents"])
                noisy_prior = self.add_noise(
                    batch_prior["latents"], noise_prior, timesteps
                )
                noise_pred_prior = model(
                    noisy_prior, timesteps,
                    batch_prior["encoder_hidden_states"]
                )

            prior_loss = self.compute_prior_preservation_loss(
                model, noise_pred, noise_pred_prior
            )
            loss = loss + self.prior_loss_weight * prior_loss

        return loss

# ============ DreamBooth with diffusers ============

from diffusers import DiffusionPipeline
import torch

pipe = DiffusionPipeline.from_pretrained(
    "stabilityai/stable-diffusion-2-1",
    torch_dtype=torch.float16,
).to("cuda")

# Configure DreamBooth training args
training_args = {
    "instance_prompt": "a sks dog",
    "class_prompt": "a dog",
    "instance_data_dir": "./instance_images",
    "class_data_dir": "./class_images",
    "with_prior_preservation": True,
    "prior_loss_weight": 1.0,
    "num_class_images": 200,
    "learning_rate": 5e-6,
    "max_train_steps": 800,
    "train_batch_size": 1,
    "gradient_accumulation_steps": 4,
    "mixed_precision": "fp16",
    "lr_scheduler": "constant",
}

print("DreamBooth training configuration:")
print(f"  Instance prompt: {training_args['instance_prompt']}")
print(f"  Class prompt: {training_args['class_prompt']}")
print(f"  Prior preservation: {training_args['with_prior_preservation']}")
print(f"  Prior loss weight: {training_args['prior_loss_weight']}")
print(f"  Steps: {training_args['max_train_steps']}")
print(f"  LR: {training_args['learning_rate']}")

# ============ LoRA for SD (Lightweight Alternative) ============

from diffusers import StableDiffusionPipeline
from peft import LoraConfig, get_peft_model

pipe = StableDiffusionPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5",
    torch_dtype=torch.float16,
).to("cuda")

# Configure LoRA
lora_config = LoraConfig(
    r=16,  # Rank of adaptation matrices
    lora_alpha=32,
    target_modules=["to_q", "to_k", "to_v", "to_out.0"],
    lora_dropout=0.1,
)

# Apply LoRA to U-Net cross-attention layers
unet = pipe.unet
unet = get_peft_model(unet, lora_config)
print(f"\\nLoRA parameters: {unet.num_parameters(only_trainable=True):,}")
print(f"  vs U-Net total: {sum(p.numel() for p in unet.parameters()):,}")
print(f"  Compression: {sum(p.numel() for p in unet.parameters()) / unet.num_parameters(only_trainable=True):.0f}x")

# Save LoRA weights (~10MB)
unet.save_pretrained("./my_lora_weights")
print("\\nDreamBooth + LoRA: production-ready personalization pipeline")`,
      output: `DreamBooth training configuration:
  Instance prompt: a sks dog
  Class prompt: a dog
  Prior preservation: True
  Prior loss weight: 1.0
  Steps: 800
  LR: 5e-6

LoRA parameters: 8,388,608
  vs U-Net total: 859,520,452
  Compression: 102x

DreamBooth + LoRA: production-ready personalization pipeline`,
      explanation: 'DreamBooth fine-tunes the U-Net on a few instance images with a unique token identifier. The prior preservation loss prevents catastrophic forgetting by maintaining the model\'s ability to generate the base class. LoRA provides a 100x more compact alternative by adding low-rank matrices to cross-attention layers, achieving comparable quality with much smaller file sizes.',
    },
  ],
  realWorld: {
    useCases: [
      { industry: 'Character Design', description: 'Studios use ControlNet (OpenPose) to ensure consistent character poses across multiple concept art iterations. DreamBooth/LoRA captures a character\'s identity (face, costume, proportions) and generates them in any scene.' },
      { industry: 'E-commerce Photography', description: 'Retailers use ControlNet (Canny + Depth) to generate product images in diverse settings while preserving product shape and structure. DreamBooth fine-tunes the model on specific products for consistent branding.' },
      { industry: 'Architecture Visualization', description: 'Architects use ControlNet (depth + HED edges) to turn rough 3D renders into photorealistic visualizations. The depth map preserves the spatial layout while the diffusion model adds materials, lighting, and context.' },
    ],
    caseStudy: {
      problem: 'A game studio needed to generate 500 concept art variations of a new character in 100 different poses and environments. Traditional concept art took 4-8 hours per piece — the full set would take 3 months.',
      solution: 'They created 8 reference illustrations of the character, trained a LoRA adapter (5 minutes on A100), then used OpenPose ControlNet to generate the character in 100 predefined poses across 5 environments. Each pose was refined with img2img ControlNet.',
      results: '500 concept art pieces generated in 2 days. The LoRA adapter (12MB) captured the character design at 97% consistency. ControlNet ensured anatomically correct poses. The studio saved $80,000 in artist costs and the game shipped 2 months ahead of schedule.',
    },
    bestPractices: [
      'Use Canny ControlNet when you need exact structural preservation (buildings, products)',
      'Use Depth ControlNet when structure matters but texture/style should be free',
      'Use OpenPose ControlNet for human/character pose control',
      'For DreamBooth: use 5-10 high-quality images with varied backgrounds and angles',
      'Prefer LoRA over DreamBooth when file size matters or training resources are limited',
      'Set prior preservation weight to 1.0 for DreamBooth — lower values risk catastrophic forgetting',
    ],
    tools: ['Hugging Face Diffusers', 'ControlNet (lllyasviel)', 'Kohya SS GUI (training)', 'Automatic1111 ControlNet extension', 'ComfyUI ControlNet nodes', 'OpenPose (CMU Perceptual Computing)'],
    jobRoles: ['Generative AI Engineer', 'AI Artist / Creative Director', 'Game Character Artist', 'ML Fine-tuning Engineer', 'Creative Technologist'],
    furtherReading: [
      '"Adding Conditional Control to Text-to-Image Diffusion Models" (Zhang & Agrawala, 2023)',
      '"DreamBooth: Fine Tuning Text-to-Image Diffusion Models for Subject-Driven Generation" (Ruiz et al., 2023)',
      '"Low-Rank Adaptation of Large Language Models" (Hu et al., 2021)',
      'Hugging Face Diffusers training documentation',
    ],
  },
  quiz: [
    {
      id: 'cd-1', type: 'mcq',
      question: 'What is the purpose of zero convolution in ControlNet?',
      options: [
        'To reduce the model size by converting all weights to zero',
        'To initialize the control pathway with zero output so it does not affect the pretrained model at the start of training',
        'To zero out gradients during backpropagation for faster training',
        'To remove noise from the conditioning input',
      ],
      correctAnswer: 'To initialize the control pathway with zero output so it does not affect the pretrained model at the start of training',
      explanation: 'Zero convolutions are initialized to output zero regardless of input. This ensures that at the start of training, ControlNet adds nothing to the frozen U-Net — the base model generates exactly as it did before. As training progresses, the zero convolutions learn to propagate the conditioning signal, preventing catastrophic forgetting of the original model.',
    },
    {
      id: 'cd-2', type: 'truefalse',
      question: 'DreamBooth\'s prior preservation loss prevents the model from forgetting how to generate the base class (e.g., "dog") while learning the specific instance.',
      correctAnswer: 'True',
      explanation: 'The prior preservation loss computes MSE between the model\'s predictions on class prompts (e.g., "a dog") and the predictions from the frozen pretrained model. This regularizes the fine-tuning to retain general class knowledge while adapting to the specific instance.',
    },
    {
      id: 'cd-3', type: 'code',
      question: 'In Multi-ControlNet, what do the two scale values control?',
      code: `pipe_multi(
    prompt, image=[canny_edges, depth_map],
    controlnet_conditioning_scale=[0.7, 0.4]
)`,
      options: [
        'The prompt adherence and image resolution',
        'The relative strength of each ControlNet (Canny=0.7, Depth=0.4)',
        'The inference steps and CFG scale',
        'The number of denoising steps for each control',
      ],
      correctAnswer: 'The relative strength of each ControlNet (Canny=0.7, Depth=0.4)',
      explanation: 'Each ControlNet has an independent conditioning scale. Here, the Canny ControlNet contributes 0.7x and the Depth ControlNet contributes 0.4x to the total noise prediction adjustment. This allows fine-grained control over which conditioning signal dominates.',
    },
    {
      id: 'cd-4', type: 'fillblank',
      question: 'DreamBooth uses a unique ___ in the prompt (e.g., "sks") to bind to the specific subject being fine-tuned.',
      correctAnswer: 'token identifier',
      explanation: 'The unique token identifier (often a rare string like "sks" or "v1") serves as a placeholder for the subject. During fine-tuning, the model learns to associate this token with the specific instance photos, enabling generation of the subject in new contexts via prompts like "a sks dog on a beach."',
    },
    {
      id: 'cd-5', type: 'match',
      question: 'Match each personalization method with its characteristic:',
      pairs: [
        { left: 'DreamBooth', right: 'Fine-tunes full U-Net, best quality, ~5GB file' },
        { left: 'LoRA', right: 'Adapts cross-attention layers, ~10MB file, popular for sharing' },
        { left: 'Textual Inversion', right: 'Learns new word embeddings, ~100KB, lowest quality' },
        { left: 'IP-Adapter', right: 'Image-prompted generation via decoupled cross-attention' },
      ],
      correctAnswer: 'All matched correctly',
      explanation: 'These four methods offer a spectrum of personalization: DreamBooth (highest quality, largest), LoRA (best quality-to-size ratio), Textual Inversion (most compact, lowest quality), and IP-Adapter (image-based rather than text-based conditioning).',
    },
  ],
}))

export {}