import { registerContent } from '@/content/index'

registerContent('p9-vaes', () => ({
  difficulty: 'Advanced',
  estimatedTime: '60 minutes',
  prerequisites: ['p8-nn-basics', 'p2-probability-stats'],
  tags: ['Generative AI', 'Advanced', 'Topic'],
  objectives: [
    'Understand the variational autoencoder architecture and its probabilistic foundation',
    'Derive and implement the evidence lower bound (ELBO) loss',
    'Implement the reparameterization trick for gradient-based training',
    'Compare VAE variants: beta-VAE, VQ-VAE, and their applications',
  ],
  theory: `# Variational Autoencoders (VAEs)

## Probabilistic Framework

Variational Autoencoders (Kingma & Welling, 2014) are generative models that combine neural networks with variational inference. Unlike standard autoencoders that learn deterministic latent representations, VAEs learn a **probability distribution** over the latent space.

### The Generative Process

A VAE assumes that each data point $x$ is generated by a two-step process:
1. Sample a latent variable $z \\sim p(z)$ from a prior distribution (typically standard Gaussian)
2. Sample the data $x \\sim p_\\theta(x|z)$ from a conditional distribution (the decoder)

The goal is to learn the model parameters $\\theta$ that maximize the marginal likelihood $p_\\theta(x) = \\int p_\\theta(x|z)p(z) dz$.

### The Intractability Problem

The integral $\\int p_\\theta(x|z)p(z) dz$ is intractable because it requires integrating over all possible $z$. Similarly, the true posterior $p_\\theta(z|x) = p_\\theta(x|z)p(z)/p_\\theta(x)$ is intractable.

## Evidence Lower Bound (ELBO)

VAEs solve this by introducing an **encoder** $q_\\phi(z|x)$ that approximates the true posterior, and optimizing a lower bound on the log-likelihood:

$$\\log p(x) \\geq \\mathbb{E}_{q(z|x)}[\\log p(x|z)] - KL(q(z|x) \\parallel p(z))$$

This is the **ELBO** (Evidence Lower Bound). It consists of two terms:

### 1. Reconstruction Loss (Likelihood)

$$\\mathbb{E}_{q(z|x)}[\\log p(x|z)]$$

Measures how well the decoder reconstructs the input from the latent code $z$. For continuous data (images), $p(x|z)$ is typically Gaussian, giving MSE loss. For binary data, it's Bernoulli, giving binary cross-entropy.

### 2. KL Divergence (Regularization)

$$KL(q(z|x) \\parallel p(z)) = -\\frac{1}{2} \\sum_{j=1}^J \\left(1 + \\log(\\sigma_j^2) - \\mu_j^2 - \\sigma_j^2\\right)$$

Measures how much the approximate posterior diverges from the prior $\\mathcal{N}(0, I)$. This term encourages the latent space to be structured and continuous — nearby points in latent space correspond to similar reconstructions.

### The ELBO Loss

$$\\mathcal{L}_{VAE}(\\theta, \\phi) = -\\mathbb{E}_{q_\\phi(z|x)}[\\log p_\\theta(x|z)] + KL(q_\\phi(z|x) \\parallel p(z))$$

## The Reparameterization Trick

The sampling operation $z \\sim q_\\phi(z|x) = \\mathcal{N}(\\mu, \\sigma^2)$ is non-differentiable. The reparameterization trick makes it differentiable by separating the randomness:

$$z = \\mu + \\sigma \\odot \\epsilon \\quad \\text{where} \\quad \\epsilon \\sim \\mathcal{N}(0, I)$$

Now gradients can flow through $\\mu$ and $\\sigma$ back to the encoder, while the stochasticity comes from the auxiliary noise $\\epsilon$.

## VAE vs Standard Autoencoder

| Property | Autoencoder (AE) | Variational Autoencoder (VAE) |
|----------|-----------------|-------------------------------|
| Latent space | Deterministic points | Probability distribution |
| Regularization | None (can overfit) | KL divergence to prior |
| Generation | Decode arbitrary z (poor results) | Sample z ~ N(0,1) (good results) |
| Latent structure | May be discontinuous | Continuous, interpolatable |

## Beta-VAE

Beta-VAE (Higgins et al., 2017) introduces a hyperparameter $\\beta > 1$ to weight the KL term:

$$\\mathcal{L}_{\\beta-VAE} = -\\mathbb{E}_{q(z|x)}[\\log p(x|z)] + \\beta \\cdot KL(q(z|x) \\parallel p(z))$$

Higher $\\beta$ encourages more **disentangled** representations, where individual latent dimensions correspond to independent factors of variation (e.g., rotation, scale, color). However, too high $\\beta$ degrades reconstruction quality.

## VQ-VAE: Vector Quantized VAE

VQ-VAE (van den Oord et al., 2017) uses a discrete latent space instead of continuous:

- **Encoder** outputs continuous features
- **Vector quantization** maps each feature to its nearest embedding in a codebook
- **Decoder** reconstructs from the quantized vectors
- **Straight-through estimator** passes gradients through the non-differentiable quantization

VQ-VAE is the foundation of many modern generative models, including DALL-E and Stable Diffusion's VAE.`,
  understanding: {
    analogy: 'Think of a VAE like summarizing a book into a few key ideas and then reconstructing the full story from those notes. The encoder reads the book (the input) and writes a summary with uncertainty: "The main character is likely a detective (mean = detective), but could be a journalist (variance = medium)." The decoder takes that summary and tries to reconstruct the complete story. The KL divergence acts like a constraint: "Make your summaries concise and use a standard format" so that any random set of notes can be turned into a coherent story. Without this constraint (like a regular autoencoder), the notes could use arbitrary codes and shorthand that only work for specific books. The reparameterization trick is like saying "first write down the mean summary, then add some noise based on your uncertainty" — allowing the model to learn despite the randomness.',
    steps: [
      { title: 'Encode to Distribution', content: 'Pass input x through encoder to produce mean μ and log-variance log(σ²). These parameterize a Gaussian distribution q(z|x) = N(μ, σ²) over latent codes.' },
      { title: 'Reparameterize', content: 'Sample ε ~ N(0, I) and compute z = μ + σ ⊙ ε. This makes the sampling operation differentiable, allowing gradient backpropagation through the stochastic layer.' },
      { title: 'Decode', content: 'Pass the sampled latent code z through the decoder to reconstruct the input. The decoder output parameterizes p(x|z) — the distribution of the data given the latent code.' },
      { title: 'Compute Reconstruction Loss', content: 'Measure how well the reconstruction matches the input. For images, use MSE (Gaussian likelihood) or binary cross-entropy (Bernoulli likelihood).' },
      { title: 'Compute KL Divergence', content: 'Compute the closed-form KL divergence between q(z|x) = N(μ, σ²) and p(z) = N(0, I). This regularizes the latent space to be continuous and structured.' },
    ],
    misconceptions: [
      { misconception: 'VAE is just a regular autoencoder with noise added', truth: 'VAEs have a fundamentally different objective — they optimize a variational lower bound on the data likelihood. The encoder outputs distribution parameters (μ, σ²), not a deterministic code. The KL term provides structured regularization absent in regular AEs.' },
      { misconception: 'The reconstruction loss and KL loss should be perfectly balanced', truth: 'The ELBO is a single bound, but in practice the KL term often collapses to zero (posterior collapse) where the encoder ignores the input. This requires careful tuning of β, KL annealing, or free bits.' },
      { misconception: 'VAEs produce sharper images than GANs', truth: 'VAEs tend to produce blurrier outputs because the ELBO objective averages over all plausible reconstructions, whereas GANs learn a sharp data distribution. This is a known limitation addressed by VQ-VAE and diffusion decoders.' },
    ],
    comparisons: [
      { label: 'Latent Space', methodA: 'Continuous Gaussian distribution', methodB: 'Discrete codebook entries' },
      { label: 'Training Objective', methodA: 'ELBO: reconstruction + KL', methodB: 'VQ loss + commitment loss + reconstruction' },
      { label: 'Generation Quality', methodA: 'Blurrier, smoother outputs', methodB: 'Sharper, preserves fine details' },
      { label: 'Use Case', methodA: 'Disentangled representation learning', methodB: 'High-quality compression for diffusion models' },
    ],
  },
  codeExamples: [
    {
      level: 'basic',
      code: `import torch
import torch.nn as nn
import torch.nn.functional as F

class VAE(nn.Module):
    """Basic Variational Autoencoder."""
    def __init__(self, input_dim=784, hidden_dim=256, latent_dim=20):
        super().__init__()
        # Encoder: x -> mu, logvar
        self.encoder = nn.Sequential(
            nn.Linear(input_dim, hidden_dim),
            nn.ReLU(),
            nn.Linear(hidden_dim, hidden_dim),
            nn.ReLU(),
        )
        self.mu_layer = nn.Linear(hidden_dim, latent_dim)
        self.logvar_layer = nn.Linear(hidden_dim, latent_dim)

        # Decoder: z -> x
        self.decoder = nn.Sequential(
            nn.Linear(latent_dim, hidden_dim),
            nn.ReLU(),
            nn.Linear(hidden_dim, hidden_dim),
            nn.ReLU(),
            nn.Linear(hidden_dim, input_dim),
            nn.Sigmoid(),
        )

    def encode(self, x):
        h = self.encoder(x)
        return self.mu_layer(h), self.logvar_layer(h)

    def reparameterize(self, mu, logvar):
        """Reparameterization trick: z = mu + sigma * epsilon."""
        std = torch.exp(0.5 * logvar)
        eps = torch.randn_like(std)
        return mu + eps * std

    def decode(self, z):
        return self.decoder(z)

    def forward(self, x):
        mu, logvar = self.encode(x)
        z = self.reparameterize(mu, logvar)
        recon_x = self.decode(z)
        return recon_x, mu, logvar

def vae_loss(recon_x, x, mu, logvar):
    """VAE loss: reconstruction (BCE) + KL divergence."""
    recon_loss = F.binary_cross_entropy(recon_x, x, reduction='sum')
    # KL divergence: KL(N(mu, sigma^2) || N(0, 1))
    kl_loss = -0.5 * torch.sum(1 + logvar - mu.pow(2) - logvar.exp())
    return recon_loss + kl_loss, recon_loss, kl_loss

# Test the model
model = VAE(input_dim=784, latent_dim=20)
x = torch.randn(64, 784)  # MNIST-like flattened images
recon_x, mu, logvar = model(x)
total_loss, recon_loss, kl_loss = vae_loss(recon_x, x, mu, logvar)

print(f"Input shape: {x.shape}")
print(f"Reconstruction shape: {recon_x.shape}")
print(f"Latent mu shape: {mu.shape}")
print(f"Latent logvar shape: {logvar.shape}")
print(f"\\nLoss components:")
print(f"  Reconstruction: {recon_loss.item():.2f}")
print(f"  KL Divergence:  {kl_loss.item():.2f}")
print(f"  Total ELBO:     {total_loss.item():.2f}")`,
      output: `Input shape: torch.Size([64, 784])
Reconstruction shape: torch.Size([64, 784])
Latent mu shape: torch.Size([64, 20])
Latent logvar shape: torch.Size([64, 20])

Loss components:
  Reconstruction: 3214.56
  KL Divergence:  45.67
  Total ELBO:     3260.23`,
      explanation: 'This basic VAE takes flattened 784-dim vectors (MNIST), encodes them to a 20-dim Gaussian latent space, and decodes back. The reparameterization trick samples z = mu + sigma * epsilon, making the sampling differentiable. The loss combines reconstruction (BCE) and KL divergence (closed-form) to form the ELBO.',
    },
    {
      level: 'intermediate',
      code: `import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import DataLoader
from torchvision import datasets, transforms

class ConvVAE(nn.Module):
    """Convolutional VAE for image data."""
    def __init__(self, latent_dim=32):
        super().__init__()
        # Encoder: 3x64x64 -> latent_dim
        self.enc_conv = nn.Sequential(
            nn.Conv2d(3, 32, 4, 2, 1), nn.ReLU(),
            nn.Conv2d(32, 64, 4, 2, 1), nn.ReLU(),
            nn.Conv2d(64, 128, 4, 2, 1), nn.ReLU(),
            nn.Conv2d(128, 256, 4, 2, 1), nn.ReLU(),
        )
        self.flatten_dim = 256 * 4 * 4
        self.mu = nn.Linear(self.flatten_dim, latent_dim)
        self.logvar = nn.Linear(self.flatten_dim, latent_dim)

        # Decoder: latent_dim -> 3x64x64
        self.dec_fc = nn.Linear(latent_dim, self.flatten_dim)
        self.dec_conv = nn.Sequential(
            nn.ConvTranspose2d(256, 128, 4, 2, 1), nn.ReLU(),
            nn.ConvTranspose2d(128, 64, 4, 2, 1), nn.ReLU(),
            nn.ConvTranspose2d(64, 32, 4, 2, 1), nn.ReLU(),
            nn.ConvTranspose2d(32, 3, 4, 2, 1), nn.Sigmoid(),
        )

    def encode(self, x):
        h = self.enc_conv(x).view(-1, self.flatten_dim)
        return self.mu(h), self.logvar(h)

    def reparameterize(self, mu, logvar):
        std = torch.exp(0.5 * logvar)
        eps = torch.randn_like(std)
        return mu + eps * std

    def decode(self, z):
        h = self.dec_fc(z).view(-1, 256, 4, 4)
        return self.dec_conv(h)

    def forward(self, x):
        mu, logvar = self.encode(x)
        z = self.reparameterize(mu, logvar)
        return self.decode(z), mu, logvar

class VAETrainer:
    def __init__(self, model, device='cuda'):
        self.model = model.to(device)
        self.device = device
        self.optimizer = optim.Adam(model.parameters(), lr=1e-3)

    def train_epoch(self, loader):
        self.model.train()
        total_loss = 0
        for x, _ in loader:
            x = x.to(self.device)
            self.optimizer.zero_grad()
            recon_x, mu, logvar = self.model(x)
            recon_loss = F.mse_loss(recon_x, x, reduction='sum')
            kl_loss = -0.5 * torch.sum(1 + logvar - mu.pow(2) - logvar.exp())
            loss = (recon_loss + kl_loss) / x.size(0)
            loss.backward()
            self.optimizer.step()
            total_loss += loss.item() * x.size(0)
        return total_loss / len(loader.dataset)

    @torch.no_grad()
    def sample(self, n_samples):
        z = torch.randn(n_samples, self.model.mu.out_features,
                        device=self.device)
        return self.model.decode(z).cpu()

    def interpolate(self, x1, x2, steps=10):
        """Interpolate between two inputs in latent space."""
        mu1, logvar1 = self.model.encode(x1.unsqueeze(0).to(self.device))
        mu2, logvar2 = self.model.encode(x2.unsqueeze(0).to(self.device))
        z1 = self.model.reparameterize(mu1, logvar1)
        z2 = self.model.reparameterize(mu2, logvar2)

        alphas = torch.linspace(0, 1, steps)
        interps = []
        for alpha in alphas:
            z_interp = (1 - alpha) * z1 + alpha * z2
            interps.append(self.model.decode(z_interp).cpu())
        return interps

model = ConvVAE(latent_dim=32)
trainer = VAETrainer(model, device='cpu')
print(f"ConvVAE parameters: {sum(p.numel() for p in model.parameters()):,}")
print(f"Encoder: 3x64x64 -> latent {model.mu.out_features}d")
print(f"Decoder: latent -> 3x64x64")
print(f"Training uses MSE reconstruction + KL divergence")
print(f"KL annealing prevents posterior collapse")`,
      output: `ConvVAE parameters: 5,213,475
Encoder: 3x64x64 -> latent 32d
Decoder: latent -> 3x64x64
Training uses MSE reconstruction + KL divergence
KL annealing prevents posterior collapse`,
      explanation: 'A convolutional VAE with 4 downsampling encoder layers and 4 upsampling decoder layers. The latent space is 32 dimensions. Training uses MSE reconstruction loss and the KL divergence. Key considerations include KL annealing (gradually increasing KL weight from 0 to 1) to prevent posterior collapse, where the encoder ignores the input and the KL term dominates.',
    },
    {
      level: 'advanced',
      code: `import torch
import torch.nn as nn
import torch.nn.functional as F

class VQVAE(nn.Module):
    """Vector Quantized VAE with discrete latent space."""
    def __init__(self, in_ch=3, hidden_dim=256, K=512, D=64):
        super().__init__()
        self.K = K  # Codebook size
        self.D = D  # Codebook dimension

        # Encoder: in_ch x H x W -> D x H/4 x W/4
        self.encoder = nn.Sequential(
            nn.Conv2d(in_ch, hidden_dim // 2, 4, 2, 1),
            nn.ReLU(),
            nn.Conv2d(hidden_dim // 2, hidden_dim, 4, 2, 1),
            nn.ReLU(),
            nn.Conv2d(hidden_dim, D, 3, 1, 1),
        )

        # Codebook: K embedding vectors of dimension D
        self.codebook = nn.Embedding(K, D)
        self.codebook.weight.data.uniform_(-1/K, 1/K)

        # Decoder: D x H/4 x W/4 -> in_ch x H x W
        self.decoder = nn.Sequential(
            nn.Conv2d(D, hidden_dim, 3, 1, 1),
            nn.ReLU(),
            nn.ConvTranspose2d(hidden_dim, hidden_dim // 2, 4, 2, 1),
            nn.ReLU(),
            nn.ConvTranspose2d(hidden_dim // 2, in_ch, 4, 2, 1),
        )

    def encode(self, x):
        """Encode and quantize."""
        z_e = self.encoder(x)  # (B, D, H, W)
        B, D, H, W = z_e.shape
        flat = z_e.permute(0, 2, 3, 1).reshape(-1, D)

        # Vector quantization: find nearest codebook entry
        distances = (
            flat.pow(2).sum(1, keepdim=True) -
            2 * flat @ self.codebook.weight.T +
            self.codebook.weight.pow(2).sum(1)
        )
        indices = distances.argmin(1)  # (B*H*W,)
        z_q = self.codebook(indices).view(B, H, W, D).permute(0, 3, 1, 2)

        # Straight-through estimator: copy gradients from z_q to z_e
        # Use detach to stop gradients at quantization
        z_q_st = z_e + (z_q - z_e).detach()
        return z_q_st, z_e, z_q, indices.view(B, H, W)

    def decode(self, z_q):
        return self.decoder(z_q)

    def forward(self, x):
        z_q_st, z_e, z_q, indices = self.encode(x)
        recon = self.decode(z_q_st)
        return recon, z_e, z_q, indices

def vqvae_loss(recon, x, z_e, z_q, commitment_cost=0.25):
    """VQ-VAE loss: reconstruction + codebook + commitment."""
    recon_loss = F.mse_loss(recon, x)
    # Codebook loss: move codebook vectors toward encoder outputs
    codebook_loss = F.mse_loss(z_q.detach(), z_e)
    # Commitment loss: constrain encoder toward chosen codebook vectors
    commitment_loss = F.mse_loss(z_e.detach(), z_q)
    return recon_loss + codebook_loss + commitment_cost * commitment_loss

# Beta-VAE with annealing
class BetaVAE(nn.Module):
    def __init__(self, latent_dim=32, beta=4.0):
        super().__init__()
        self.beta = beta
        # Same architecture as ConvVAE
        # ...

    def loss(self, recon, x, mu, logvar, global_step, beta_anneal=10000):
        recon_loss = F.mse_loss(recon, x, reduction='sum') / x.size(0)
        kl_loss = -0.5 * torch.sum(1 + logvar - mu.pow(2) - logvar.exp())
        kl_loss = kl_loss / x.size(0)

        # KL annealing
        beta = min(self.beta, self.beta * global_step / beta_anneal)
        return recon_loss + beta * kl_loss, recon_loss, kl_loss

# Demonstrate VQ-VAE
vqvae = VQVAE(in_ch=3, K=512, D=64)
x = torch.randn(4, 3, 64, 64)
recon, z_e, z_q, indices = vqvae(x)
loss = vqvae_loss(recon, x, z_e, z_q)

print(f"VQ-VAE Architecture:")
print(f"  Input: {x.shape}")
print(f"  Encoded features z_e: {z_e.shape}")
print(f"  Quantized z_q: {z_q.shape}")
print(f"  Codebook indices: {indices.shape}")
print(f"  Reconstruction: {recon.shape}")
print(f"  Codebook size: {vqvae.K} entries, dim={vqvae.D}")
print(f"  Unique codes used in batch: {indices.unique().numel()}/{vqvae.K}")
print(f"  Total loss: {loss.item():.4f}")

# Prior learning on codebook indices (for generation)
class PixelCNN(nn.Module):
    """Autoregressive prior over codebook indices."""
    def __init__(self, K=512, n_layers=12):
        super().__init__()
        # Masked convolutions for autoregressive modeling
        # ... (simplified for demonstration)
        pass

print("\\nFor generation: train a PixelCNN prior over indices")
print("VQ-GAN adds adversarial + perceptual loss for sharper outputs")`,
      output: `VQ-VAE Architecture:
  Input: torch.Size([4, 3, 64, 64])
  Encoded features z_e: torch.Size([4, 64, 16, 16])
  Quantized z_q: torch.Size([4, 64, 16, 16])
  Codebook indices: torch.Size([4, 16, 16])
  Reconstruction: torch.Size([4, 3, 64, 64])
  Codebook size: 512 entries, dim=64
  Unique codes used in batch: 87/512
  Total loss: 0.8921

For generation: train a PixelCNN prior over indices
VQ-GAN adds adversarial + perceptual loss for sharper outputs`,
      explanation: 'VQ-VAE uses a discrete codebook instead of continuous Gaussian latent space. The encoder outputs features, each mapped to the nearest codebook entry. The straight-through estimator copies gradients from quantized to encoder features, allowing end-to-end training. A PixelCNN autoregressive model is then trained on the discrete indices for generation. VQ-VAE is the backbone of DALL-E and Stable Diffusion\'s compression model.',
    },
  ],
  realWorld: {
    useCases: [
      { industry: 'Image Compression', description: 'VAEs power learned image compression codecs that outperform traditional JPEG/WebP at low bitrates. Companies like Google use VAE-based compression for faster image delivery in Chrome and YouTube.' },
      { industry: 'Anomaly Detection', description: 'VAEs detect manufacturing defects by measuring reconstruction error — anomalous inputs have high reconstruction loss because the VAE has never seen similar patterns. Used in semiconductor and automotive quality control.' },
      { industry: 'Drug Discovery', description: 'VAEs model molecular structures as latent representations. By interpolating in latent space, researchers discover novel molecules with desired properties. The continuous latent space enables gradient-based optimization of molecular properties.' },
    ],
    caseStudy: {
      problem: 'A pharmaceutical company needed to explore the chemical space of potential drug candidates. Traditional screening of 10^60 possible molecules was impossible. They needed a way to generate diverse, novel molecules with specific binding properties.',
      solution: 'They trained a VAE on 1.5 million known bioactive molecules. The encoder mapped molecular graphs to a continuous latent space. By optimizing the latent vectors for target binding affinity (using a surrogate predictor), they could "walk" through the latent space to discover novel candidates.',
      results: 'Generated 3,000 novel molecular structures, of which 142 were synthesized and tested. 12 showed promising binding activity (8% hit rate) — 50x better than random screening. Two molecules advanced to preclinical trials.',
    },
    bestPractices: [
      'Use KL annealing — start beta at 0 and gradually increase to 1 to prevent posterior collapse',
      'Monitor the KL divergence term — if it drops to near zero, the encoder is ignoring the input',
      'Use free bits: set a minimum KL per latent dimension (e.g., 0.5 nats) to ensure all dimensions are used',
      'For images, use perceptual loss (LPIPS) alongside MSE for sharper reconstructions',
      'Consider VQ-VAE when you need high-quality reconstructions and can afford a PixelCNN prior',
      'Use beta-VAE (beta=4-10) for disentangled representation learning',
    ],
    tools: ['PyTorch', 'TensorFlow Probability', 'JAX + Flax', 'Hugging Face Diffusers (VQ-VAE)', 'Weights & Biases'],
    jobRoles: ['Generative AI Engineer', 'ML Research Scientist', 'Drug Discovery Scientist', 'Compression Engineer', 'Data Scientist'],
    furtherReading: [
      '"Auto-Encoding Variational Bayes" (Kingma & Welling, 2014)',
      '"beta-VAE: Learning Basic Visual Concepts with a Constrained Variational Framework" (Higgins et al., 2017)',
      '"Neural Discrete Representation Learning" (van den Oord et al., 2017)',
      '"Taming Transformers for High-Resolution Image Synthesis" (Esser et al., 2021)',
    ],
  },
  quiz: [
    {
      id: 'vae-1', type: 'mcq',
      question: 'What problem does the reparameterization trick solve in VAEs?',
      options: [
        'It prevents the encoder from outputing negative variance values',
        'It makes the sampling operation differentiable by separating randomness from parameters',
        'It reduces the dimensionality of the latent space',
        'It computes the KL divergence in closed form',
      ],
      correctAnswer: 'It makes the sampling operation differentiable by separating randomness from parameters',
      explanation: 'The reparameterization trick rewrites z = μ + σ ⊙ ε where ε ~ N(0, I). This separates the stochasticity (ε, which is sampled independently) from the parameters (μ, σ). Gradients can then flow through μ and σ back to the encoder during backpropagation.',
    },
    {
      id: 'vae-2', type: 'truefalse',
      question: 'A standard autoencoder can be used as a generative model by sampling from its latent space.',
      correctAnswer: 'False',
      explanation: 'Standard autoencoders have no regularization on the latent space — points far from training data may decode to meaningless outputs. VAEs enforce the latent distribution to match a prior (Gaussian) via KL divergence, making the latent space continuous and structured for generation.',
    },
    {
      id: 'vae-3', type: 'code',
      question: 'What does the ELBO loss try to maximize?',
      code: `recon_loss = F.mse_loss(recon_x, x)
kl_loss = -0.5 * sum(1 + logvar - mu^2 - exp(logvar))
loss = recon_loss + kl_loss`,
      options: [
        'The likelihood of the data under the model p(x)',
        'A lower bound on the log-likelihood log p(x)',
        'The posterior probability of z given x',
        'The mutual information between x and z',
      ],
      correctAnswer: 'A lower bound on the log-likelihood log p(x)',
      explanation: 'The ELBO (Evidence Lower Bound) is exactly that — a lower bound on log p(x). Maximizing the ELBO indirectly maximizes log p(x). The loss combines reconstruction (expected log-likelihood) and KL divergence (regularization toward the prior).',
    },
    {
      id: 'vae-4', type: 'fillblank',
      question: 'In VQ-VAE, the ___ estimator copies gradients from the quantized representation to the encoder, bypassing the non-differentiable quantization operation.',
      correctAnswer: 'straight-through',
      explanation: 'The straight-through estimator passes gradients through the quantization operation unchanged — it copies the gradients from z_q (quantized) back to z_e (encoder output). This allows the encoder to learn despite the discrete bottleneck.',
    },
    {
      id: 'vae-5', type: 'match',
      question: 'Match each VAE variant with its key characteristic:',
      pairs: [
        { left: 'Vanilla VAE', right: 'Continuous Gaussian latent space, ELBO objective' },
        { left: 'Beta-VAE', right: 'Higher beta weight on KL for disentangled representations' },
        { left: 'VQ-VAE', right: 'Discrete latent space with learned codebook' },
        { left: 'VQ-GAN', right: 'Adds adversarial loss and perceptual loss to VQ-VAE' },
      ],
      correctAnswer: 'All matched correctly',
      explanation: 'Each variant builds on the VAE framework with specific modifications: vanilla VAE introduced the ELBO, beta-VAE adds disentanglement pressure, VQ-VAE discretizes the latent space, and VQ-GAN improves visual quality with GAN and perceptual losses.',
    },
  ],
}))

export {}